"""2st migration

Revision ID: dc9043396cdb
Revises: a248267c9f5a
Create Date: 2021-06-17 22:51:00.060534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc9043396cdb'
down_revision = 'a248267c9f5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('number', sa.String(), nullable=True))
    op.add_column('contracts', sa.Column('dateopencontract', sa.Date(), nullable=True))
    op.add_column('contracts', sa.Column('dateclosecontract', sa.Date(), nullable=True))
    op.add_column('contracts', sa.Column('numbertrudbook', sa.String(), nullable=True))
    op.drop_column('contracts', 'lastName')
    op.drop_column('contracts', 'birthday')
    op.drop_column('contracts', 'firstName')
    op.drop_column('contracts', 'secondName')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('secondName', sa.VARCHAR(), nullable=True))
    op.add_column('contracts', sa.Column('firstName', sa.VARCHAR(), nullable=True))
    op.add_column('contracts', sa.Column('birthday', sa.DATE(), nullable=True))
    op.add_column('contracts', sa.Column('lastName', sa.VARCHAR(), nullable=True))
    op.drop_column('contracts', 'numbertrudbook')
    op.drop_column('contracts', 'dateclosecontract')
    op.drop_column('contracts', 'dateopencontract')
    op.drop_column('contracts', 'number')
    # ### end Alembic commands ###
